services:
  - type: web
    name: infill-web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: infill-redis
          property: connectionString

  - type: redis
    name: infill-redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []
